version: "3.7"

services:

  app:
    container_name: "app"
    build:
      context: ./
      target: development
    volumes:
    - .:/usr/src/app
    command: npm start
    environment:
      NODE_ENV: development